### PR TITLE
Introducing material design

### PR DESCRIPTION
**Pull request by AdityaAnand1**
Updated a few versions and added material design to HomeActivity.

I suggest you try building my fork first to ensure everything works fine before merging. [Here's](https://www.dropbox.com/s/97943tmorh3bjh5/blockthis-debug-13July.apk?dl=0) the debug apk for convenience.

### CODE REVIEW

**Comment by ggsava** [comment]
Whoah! Looks really nice! A lot of work done.. I will do a thorough testing and if everything is fine I will merge it in a day or two and prepare a release. Thanks a lot.

**Comment by AdityaAnand1** [comment]
Do let me know if you find something confusing or want me to explain anything.

Also, just a heads up- disregard the first commit "[New Dependencies](https://github.com/ggsava/block-this/pull/6/commits/f9ae72f4d47fe9dd74decc8801756fb4836e990c)" I accidentally committed a different file, then gave up trying to figure out how to undo a commit so I just overwrote it in "[Last commit was the wrong build.gradle](https://github.com/ggsava/block-this/pull/6/commits/4e57e99b039f08e36183b2c749c41a2f328fa498)"

**Comment by ggsava** [comment]
@AdityaAnand1 I looked at it and it looks good, I'm just not sure whether it makes sense to merge it in before the other pages are done too, as now this one page has an entirely different design than the rest. What do you think?

**Comment by AdityaAnand1** [comment]
Yes, absolutely. It makes sense to update the main branch only when all the pages are done.

**Pull request closed without merging**
